package com.studysync;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;

/** JavaFX desktop entry point for StudySync 2.0. */
public class StudySyncApplication extends Application {
    private StudySyncService service; private BorderPane root; private final VBox navigation=new VBox(8);
    private static final DateTimeFormatter DATE_TIME_FORMAT=DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a");
    @Override public void start(Stage stage){service=new StudySyncService(new DatabaseManager());root=new BorderPane();root.getStyleClass().add("app-root");root.setTop(createHeader());root.setLeft(createNavigation());showDashboard();Scene scene=new Scene(root,1100,700);scene.getStylesheets().add(getClass().getResource("/com/studysync/studysync.css").toExternalForm());stage.setTitle("StudySync");stage.setMinWidth(900);stage.setMinHeight(600);stage.setScene(scene);stage.show();}
    private HBox createHeader(){VBox branding=new VBox(3,styledLabel("StudySync","app-title"),styledLabel("Plan. Study. Progress.","app-subtitle"));HBox h=new HBox(branding);h.setAlignment(Pos.CENTER_LEFT);h.setPadding(new Insets(18,28,18,28));h.getStyleClass().add("app-header");return h;}
    private VBox createNavigation(){Button d=navigationButton("Dashboard",this::showDashboard),c=navigationButton("Courses",this::showCourses),a=navigationButton("Assignments",this::showAssignments),s=navigationButton("Study Sessions",this::showStudySessions),w=navigationButton("Workload",this::showWorkload);navigation.getChildren().setAll(d,c,a,s,w);setActiveNavigation(d);navigation.setPadding(new Insets(24,14,24,14));navigation.setPrefWidth(205);navigation.getStyleClass().add("navigation");return navigation;}
    private Button navigationButton(String text,Runnable action){Button b=new Button(text);b.setMaxWidth(Double.MAX_VALUE);b.getStyleClass().add("navigation-button");b.setOnAction(e->{setActiveNavigation(b);action.run();});return b;}
    private void setActiveNavigation(Button active){navigation.getChildren().stream().filter(Button.class::isInstance).map(Button.class::cast).forEach(b->b.getStyleClass().remove("navigation-button-active"));active.getStyleClass().add("navigation-button-active");}
    private void showDashboard(){DashboardSummary s=service.getDashboardSummary();GridPane g=new GridPane();g.setHgap(16);g.setVgap(16);g.add(createMetricCard("Courses",s.totalCourses()),0,0);g.add(createMetricCard("Pending",s.pendingAssignments()),1,0);g.add(createMetricCard("Completed",s.completedAssignments()),2,0);g.add(createMetricCard("Overdue",s.overdueAssignments()),0,1);g.add(createMetricCard("Study Minutes",s.totalStudyMinutes()),1,1);g.add(createMetricCard("Completion",String.format("%.1f%%",s.completionPercentage())),2,1);for(int i=0;i<3;i++){ColumnConstraints c=new ColumnConstraints();c.setPercentWidth(33.333);c.setHgrow(Priority.ALWAYS);g.getColumnConstraints().add(c);}setPage(pageContainer("Dashboard","A quick view of your courses, assignments, and study progress.",g));}
    private void showCourses(){TextField code=new TextField(),name=new TextField();code.setPromptText("e.g. CSCI 2302");name.setPromptText("e.g. Data Structures & Algorithms");Button add=primary("Add Course");GridPane form=formGrid();form.add(new Label("Course Code"),0,0);form.add(code,1,0);form.add(new Label("Course Name"),0,1);form.add(name,1,1);form.add(add,1,2);VBox list=new VBox(10);refreshCourseList(list);add.setOnAction(e->{if(code.getText().isBlank()||name.getText().isBlank()){showError("Missing course information","Enter both a course code and course name.");return;}try{service.createCourse(name.getText().trim(),code.getText().trim());name.clear();code.clear();refreshCourseList(list);}catch(RuntimeException ex){showError("Could not add course",safeMessage(ex));}});setPage(pageContainer("Courses","Add courses and keep your academic schedule organized.",new VBox(18,card("Add a Course",form),card("Your Courses",list))));}
    private void refreshCourseList(VBox list){List<Course> courses=service.getCourses();list.getChildren().clear();if(courses.isEmpty()){addEmpty(list,"No courses yet. Add your first course above.");return;}for(Course c:courses){HBox row=new HBox(new VBox(3,styledLabel(c.getCode(),"course-code"),styledLabel(c.getName(),"course-name")));row.setPadding(new Insets(14));row.getStyleClass().add("course-row");list.getChildren().add(row);}}
    private void showAssignments(){List<Course> courses=service.getCourses();if(courses.isEmpty()){setPage(pageContainer("Assignments","Manage deadlines, priorities, and completion status.",card("Assignments",styledLabel("Add a course before creating assignments.","placeholder-message"))));return;}ComboBox<Course> course=new ComboBox<>();course.getItems().addAll(courses);course.getSelectionModel().selectFirst();course.setMaxWidth(Double.MAX_VALUE);TextField title=new TextField(),desc=new TextField(),time=new TextField("23:59");title.setPromptText("Assignment title");desc.setPromptText("Description (optional)");DatePicker date=new DatePicker(LocalDate.now().plusDays(1));ComboBox<Assignment.Priority> priority=new ComboBox<>();priority.getItems().addAll(Assignment.Priority.values());priority.setValue(Assignment.Priority.MEDIUM);Button add=primary("Add Assignment");GridPane form=formGrid();String[] labels={"Course","Title","Description","Due Date","Due Time","Priority"};Node[] inputs={course,title,desc,date,time,priority};for(int i=0;i<labels.length;i++){form.add(new Label(labels[i]),0,i);form.add(inputs[i],1,i);}form.add(add,1,6);TextField search=new TextField();search.setPromptText("Search title or description");ComboBox<String> filter=new ComboBox<>();filter.getItems().addAll("All","Pending","Completed","Overdue","High Priority","Medium Priority","Low Priority");filter.setValue("All");Button clear=new Button("Clear");clear.getStyleClass().add("secondary-button");HBox tools=new HBox(10,search,filter,clear);HBox.setHgrow(search,Priority.ALWAYS);VBox list=new VBox(10);Runnable refresh=()->refreshAssignmentList(list,search.getText(),filter.getValue());refresh.run();search.textProperty().addListener((o,x,y)->refresh.run());filter.setOnAction(e->refresh.run());clear.setOnAction(e->{search.clear();filter.setValue("All");});add.setOnAction(e->{if(title.getText().isBlank()){showError("Missing assignment title","Enter a title before adding the assignment.");return;}if(date.getValue()==null){showError("Missing due date","Choose a due date.");return;}try{service.createAssignment(course.getValue().getId(),title.getText().trim(),desc.getText().trim(),LocalDateTime.of(date.getValue(),parseTime(time.getText())),priority.getValue());title.clear();desc.clear();refresh.run();}catch(DateTimeParseException ex){showError("Invalid due time","Use 24-hour HH:mm format, such as 14:30 or 23:59.");}catch(RuntimeException ex){showError("Could not add assignment",safeMessage(ex));}});setPage(pageContainer("Assignments","Manage deadlines, priorities, and completion status.",new VBox(18,card("Add an Assignment",form),card("Find Assignments",tools),card("Your Assignments",list))));}
    private void refreshAssignmentList(VBox list,String query,String filter){List<Assignment> items=service.getAssignments();if(query!=null&&!query.isBlank()){String q=query.trim().toLowerCase();items=items.stream().filter(a->a.getTitle().toLowerCase().contains(q)||a.getDescription().toLowerCase().contains(q)).toList();}if(filter!=null)items=switch(filter){case "Pending"->items.stream().filter(a->!a.isCompleted()).toList();case "Completed"->items.stream().filter(Assignment::isCompleted).toList();case "Overdue"->items.stream().filter(Assignment::isOverdue).toList();case "High Priority"->items.stream().filter(a->a.getPriority()==Assignment.Priority.HIGH).toList();case "Medium Priority"->items.stream().filter(a->a.getPriority()==Assignment.Priority.MEDIUM).toList();case "Low Priority"->items.stream().filter(a->a.getPriority()==Assignment.Priority.LOW).toList();default->items;};list.getChildren().clear();if(items.isEmpty()){addEmpty(list,"No assignments match the current view.");return;}for(Assignment a:items)list.getChildren().add(assignmentRow(a,list,query,filter));}
    private HBox assignmentRow(Assignment a,VBox target,String query,String filter){Label title=styledLabel(a.getTitle(),"assignment-title"),meta=styledLabel("Due "+a.getDueDate().format(DATE_TIME_FORMAT)+"  •  "+a.getPriority()+"  •  "+(a.isCompleted()?"Completed":a.isOverdue()?"Overdue":"Pending"),"assignment-meta"),desc=styledLabel(a.getDescription().isBlank()?"No description":a.getDescription(),"course-name");desc.setWrapText(true);VBox details=new VBox(4,title,meta,desc);HBox.setHgrow(details,Priority.ALWAYS);Button status=new Button(a.isCompleted()?"Reopen":"Complete");status.getStyleClass().add("secondary-button");Button delete=new Button("Delete");delete.getStyleClass().add("danger-button");status.setOnAction(e->{try{if(a.isCompleted())service.reopenAssignment(a.getId());else service.completeAssignment(a.getId());refreshAssignmentList(target,query,filter);}catch(RuntimeException ex){showError("Could not update assignment",safeMessage(ex));}});delete.setOnAction(e->{Alert confirm=new Alert(Alert.AlertType.CONFIRMATION,"Delete \""+a.getTitle()+"\"?",ButtonType.OK,ButtonType.CANCEL);confirm.setHeaderText("Delete assignment");confirm.showAndWait().filter(ButtonType.OK::equals).ifPresent(x->{try{service.deleteAssignment(a.getId());refreshAssignmentList(target,query,filter);}catch(RuntimeException ex){showError("Could not delete assignment",safeMessage(ex));}});});HBox row=new HBox(10,details,status,delete);row.setAlignment(Pos.CENTER_LEFT);row.setPadding(new Insets(14));row.getStyleClass().add("course-row");return row;}
    private void showStudySessions(){List<Course> courses=service.getCourses();if(courses.isEmpty()){setPage(pageContainer("Study Sessions","Record and review focused study time.",card("Study Sessions",styledLabel("Add a course before recording study sessions.","placeholder-message"))));return;}ComboBox<Course> course=new ComboBox<>();course.getItems().addAll(courses);course.getSelectionModel().selectFirst();course.setMaxWidth(Double.MAX_VALUE);DatePicker date=new DatePicker(LocalDate.now());TextField time=new TextField(LocalTime.now().withSecond(0).withNano(0).toString()),duration=new TextField(),notes=new TextField();duration.setPromptText("Minutes");notes.setPromptText("What did you study? (optional)");Button record=primary("Record Session");GridPane form=formGrid();String[] labels={"Course","Date","Start Time","Duration","Notes"};Node[] inputs={course,date,time,duration,notes};for(int i=0;i<labels.length;i++){form.add(new Label(labels[i]),0,i);form.add(inputs[i],1,i);}form.add(record,1,5);VBox list=new VBox(10);refreshStudySessionList(list);record.setOnAction(e->{if(date.getValue()==null){showError("Missing session date","Choose the study-session date.");return;}try{int minutes=Integer.parseInt(duration.getText().trim());if(minutes<=0){showError("Invalid duration","Duration must be greater than zero minutes.");return;}service.recordStudySession(course.getValue().getId(),LocalDateTime.of(date.getValue(),parseTime(time.getText())),minutes,notes.getText().trim());showStudySessions();}catch(NumberFormatException ex){showError("Invalid duration","Duration must be a whole number of minutes.");}catch(DateTimeParseException ex){showError("Invalid start time","Use 24-hour HH:mm format, such as 09:30 or 18:45.");}catch(RuntimeException ex){showError("Could not record session",safeMessage(ex));}});setPage(pageContainer("Study Sessions","Record and review focused study time.",new VBox(18,card("Record a Study Session",form),card("Study History",new VBox(10,styledLabel("Total study time: "+service.getTotalStudyMinutes()+" minutes","study-total"),list)))));}
    private void refreshStudySessionList(VBox list){List<StudySession> sessions=service.getStudySessions();list.getChildren().clear();if(sessions.isEmpty()){addEmpty(list,"No study sessions recorded yet.");return;}List<Course> courses=service.getCourses();for(StudySession s:sessions){Course c=courses.stream().filter(x->x.getId()==s.getCourseId()).findFirst().orElse(null);HBox row=new HBox(new VBox(4,styledLabel((c==null?"Course #"+s.getCourseId():c.getCode())+" • "+s.getDurationMinutes()+" minutes","assignment-title"),styledLabel(s.getStartTime().format(DATE_TIME_FORMAT),"assignment-meta"),styledLabel(s.getNotes().isBlank()?"No notes":s.getNotes(),"course-name")));row.setPadding(new Insets(14));row.getStyleClass().add("course-row");list.getChildren().add(row);}}
    private void showWorkload(){ComboBox<Integer> window=new ComboBox<>();window.getItems().addAll(3,7,14,30);window.setValue(7);Button refresh=primary("Refresh Plan");HBox controls=new HBox(10,new Label("Plan next"),window,new Label("days"),refresh);controls.setAlignment(Pos.CENTER_LEFT);VBox list=new VBox(10);Label summary=styledLabel("","study-total");Runnable load=()->refreshWorkload(list,summary,window.getValue());load.run();refresh.setOnAction(e->load.run());window.setOnAction(e->load.run());setPage(pageContainer("Workload","Plan upcoming assignments and focus on the deadlines ahead.",new VBox(18,card("Planning Window",controls),card("Upcoming Workload",new VBox(12,summary,list)))));}
    private void refreshWorkload(VBox list,Label summary,int days){try{List<Assignment> upcoming=service.getUpcomingAssignments(days);list.getChildren().clear();summary.setText(upcoming.size()+" upcoming assignment"+(upcoming.size()==1?"":"s")+" in the next "+days+" days");if(upcoming.isEmpty()){addEmpty(list,"Nothing is due in this planning window.");return;}for(Assignment a:upcoming){long remaining=java.time.Duration.between(LocalDateTime.now(),a.getDueDate()).toDays();Label urgency=styledLabel(remaining<=1?"Due very soon":remaining<=3?"Due soon":"Upcoming","workload-urgency");HBox row=new HBox(new VBox(4,styledLabel(a.getTitle(),"assignment-title"),styledLabel("Due "+a.getDueDate().format(DATE_TIME_FORMAT)+"  •  "+a.getPriority(),"assignment-meta")));row.setPadding(new Insets(14));row.getStyleClass().add("course-row");list.getChildren().add(new VBox(6,urgency,row));}}catch(RuntimeException ex){showError("Could not load workload",safeMessage(ex));}}
    private LocalTime parseTime(String text){return LocalTime.parse(text.trim(),DateTimeFormatter.ofPattern("H:mm"));}
    private String safeMessage(RuntimeException ex){return ex.getMessage()==null||ex.getMessage().isBlank()?"An unexpected error occurred.":ex.getMessage();}
    private Button primary(String text){Button b=new Button(text);b.getStyleClass().add("primary-button");return b;}
    private GridPane formGrid(){GridPane f=new GridPane();f.setHgap(12);f.setVgap(10);ColumnConstraints input=new ColumnConstraints();input.setHgrow(Priority.ALWAYS);f.getColumnConstraints().addAll(new ColumnConstraints(),input);return f;}
    private Label styledLabel(String text,String style){Label l=new Label(text);l.getStyleClass().add(style);return l;}
    private void addEmpty(VBox list,String text){list.getChildren().add(styledLabel(text,"placeholder-message"));}
    private VBox card(String title,Node content){VBox c=new VBox(12,styledLabel(title,"card-title"),content);c.setPadding(new Insets(20));c.getStyleClass().add("content-card");return c;}
    private void showError(String title,String message){Alert a=new Alert(Alert.AlertType.ERROR);a.setTitle("StudySync");a.setHeaderText(title);a.setContentText(message);a.showAndWait();}
    private VBox pageContainer(String title,String description,Node content){VBox p=new VBox(12,styledLabel(title,"section-title"),styledLabel(description,"section-description"),content);p.setPadding(new Insets(30));VBox.setMargin(content,new Insets(14,0,0,0));return p;}
    private void setPage(Node page){ScrollPane s=new ScrollPane(page);s.setFitToWidth(true);s.setFitToHeight(true);s.getStyleClass().add("content-scroll");root.setCenter(s);}
    private VBox createMetricCard(String label,Object value){VBox c=new VBox(6,styledLabel(String.valueOf(value),"metric-value"),styledLabel(label,"metric-label"));c.setPadding(new Insets(20));c.setMinHeight(120);c.setMaxWidth(Double.MAX_VALUE);c.getStyleClass().add("metric-card");return c;}
    public static void main(String[] args){launch(args);}
}
