package com.studysync;

import java.time.DayOfWeek;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.TemporalAdjusters;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.stream.Collectors;

/** Application service that coordinates StudySync's core productivity features. */
public class StudySyncService {
    private static final String DAILY_STUDY_TARGET_KEY="daily_study_target_minutes"; private static final String COURSE_STUDY_TARGET_PREFIX="course_study_target_minutes_"; private static final int DEFAULT_DAILY_STUDY_TARGET=120; private static final int DEFAULT_COURSE_STUDY_TARGET=180; private final DatabaseManager databaseManager;
    public StudySyncService(DatabaseManager databaseManager){if(databaseManager==null)throw new IllegalArgumentException("Database manager cannot be null.");this.databaseManager=databaseManager;}
    public Course createCourse(String name,String code){return databaseManager.addCourse(name,code);} public List<Course> getCourses(){return databaseManager.getAllCourses();} public boolean updateCourse(int id,String name,String code){requireCourse(id);Course c=new Course(id,name,code);return databaseManager.updateCourse(id,c.getName(),c.getCode());} public boolean deleteCourse(int id){requireCourse(id);return databaseManager.deleteCourse(id);}
    public Assignment createAssignment(int courseId,String title,String description,LocalDateTime dueDate,Assignment.Priority priority){requireCourse(courseId);return databaseManager.addAssignment(courseId,title,description,dueDate,priority);} public List<Assignment> getAssignments(){return databaseManager.getAllAssignments();} public List<Assignment> getAssignmentsForCourse(int id){requireCourse(id);return databaseManager.getAssignmentsByCourse(id);} public List<Assignment> getPendingAssignments(){return databaseManager.getAllAssignments().stream().filter(a->!a.isCompleted()).sorted(Comparator.comparing(Assignment::getDueDate)).toList();} public List<Assignment> getCompletedAssignments(){return databaseManager.getAllAssignments().stream().filter(Assignment::isCompleted).sorted(Comparator.comparing(Assignment::getDueDate)).toList();} public List<Assignment> getOverdueAssignments(){return databaseManager.getAllAssignments().stream().filter(Assignment::isOverdue).sorted(Comparator.comparing(Assignment::getDueDate)).toList();}
    public List<Assignment> getUpcomingAssignments(int days){if(days<=0)throw new IllegalArgumentException("Upcoming assignment window must be greater than zero days.");LocalDateTime now=LocalDateTime.now(),deadline=now.plusDays(days);return databaseManager.getAllAssignments().stream().filter(a->!a.isCompleted()).filter(a->!a.getDueDate().isBefore(now)).filter(a->!a.getDueDate().isAfter(deadline)).sorted(Comparator.comparing(Assignment::getDueDate)).toList();} public List<Assignment> getAssignmentsByPriority(Assignment.Priority priority){if(priority==null)throw new IllegalArgumentException("Assignment priority cannot be null.");return databaseManager.getAllAssignments().stream().filter(a->a.getPriority()==priority).sorted(Comparator.comparing(Assignment::getDueDate)).toList();} public List<Assignment> searchAssignments(String query){if(query==null||query.isBlank())throw new IllegalArgumentException("Search query cannot be empty.");String q=query.trim().toLowerCase(Locale.ROOT);return databaseManager.getAllAssignments().stream().filter(a->a.getTitle().toLowerCase(Locale.ROOT).contains(q)||a.getDescription().toLowerCase(Locale.ROOT).contains(q)).sorted(Comparator.comparing(Assignment::getDueDate)).toList();}
    public List<AssignmentPlanItem> getAssignmentPlan(){return getAssignmentPlan(LocalDateTime.now());} public List<AssignmentPlanItem> getAssignmentPlan(LocalDateTime t){if(t==null)throw new IllegalArgumentException("Assignment plan reference time cannot be null.");return databaseManager.getAllAssignments().stream().filter(a->!a.isCompleted()).map(a->new AssignmentPlanItem(a,classifyUrgency(a,t),Duration.between(t,a.getDueDate()).toMinutes())).sorted(Comparator.comparingInt((AssignmentPlanItem i)->urgencyRank(i.urgency())).thenComparingInt(i->priorityRank(i.assignment().getPriority())).thenComparing(i->i.assignment().getDueDate()).thenComparingInt(i->i.assignment().getId())).toList();} private AssignmentPlanItem.Urgency classifyUrgency(Assignment a,LocalDateTime t){if(a.getDueDate().isBefore(t))return AssignmentPlanItem.Urgency.OVERDUE;if(a.getDueDate().toLocalDate().equals(t.toLocalDate()))return AssignmentPlanItem.Urgency.DUE_TODAY;if(!a.getDueDate().isAfter(t.plusHours(48)))return AssignmentPlanItem.Urgency.DUE_SOON;return AssignmentPlanItem.Urgency.UPCOMING;} private int urgencyRank(AssignmentPlanItem.Urgency u){return switch(u){case OVERDUE->0;case DUE_TODAY->1;case DUE_SOON->2;case UPCOMING->3;};} private int priorityRank(Assignment.Priority p){return switch(p){case HIGH->0;case MEDIUM->1;case LOW->2;};}
    public boolean updateAssignment(int id,int courseId,String title,String description,LocalDateTime dueDate,Assignment.Priority priority){requireAssignment(id);requireCourse(courseId);Assignment a=new Assignment(courseId,title,description,dueDate,priority);return databaseManager.updateAssignment(id,a.getCourseId(),a.getTitle(),a.getDescription(),a.getDueDate(),a.getPriority());} public boolean deleteAssignment(int id){requireAssignment(id);return databaseManager.deleteAssignment(id);} public boolean completeAssignment(int id){requireAssignment(id);return databaseManager.setAssignmentCompleted(id,true);} public boolean reopenAssignment(int id){requireAssignment(id);return databaseManager.setAssignmentCompleted(id,false);}
    public StudySession recordStudySession(int courseId,LocalDateTime start,int minutes,String notes){requireCourse(courseId);return databaseManager.addStudySession(courseId,start,minutes,notes);} public List<StudySession> getStudySessions(){return databaseManager.getAllStudySessions();} public List<StudySession> getStudySessionsForCourse(int id){requireCourse(id);return databaseManager.getStudySessionsByCourse(id);} public boolean updateStudySession(int id,int courseId,LocalDateTime start,int minutes,String notes){requireStudySession(id);requireCourse(courseId);StudySession s=new StudySession(courseId,start,minutes,notes);return databaseManager.updateStudySession(id,s.getCourseId(),s.getStartTime(),s.getDurationMinutes(),s.getNotes());} public boolean deleteStudySession(int id){requireStudySession(id);return databaseManager.deleteStudySession(id);} public int getTotalStudyMinutes(){return databaseManager.getAllStudySessions().stream().mapToInt(StudySession::getDurationMinutes).sum();} public int getTotalStudyMinutesForCourse(int id){requireCourse(id);return databaseManager.getStudySessionsByCourse(id).stream().mapToInt(StudySession::getDurationMinutes).sum();}
    public int getDailyStudyTargetMinutes(){String saved=databaseManager.getSetting(DAILY_STUDY_TARGET_KEY);if(saved==null)return DEFAULT_DAILY_STUDY_TARGET;try{int v=Integer.parseInt(saved);return v>0?v:DEFAULT_DAILY_STUDY_TARGET;}catch(NumberFormatException e){return DEFAULT_DAILY_STUDY_TARGET;}} public void setDailyStudyTargetMinutes(int target){if(target<=0)throw new IllegalArgumentException("Study goal target must be greater than zero.");databaseManager.setSetting(DAILY_STUDY_TARGET_KEY,Integer.toString(target));} public DailyStudyGoal getDailyStudyGoal(){return getDailyStudyGoal(LocalDate.now(),getDailyStudyTargetMinutes());} public DailyStudyGoal getDailyStudyGoal(int target){return getDailyStudyGoal(LocalDate.now(),target);} public DailyStudyGoal getDailyStudyGoal(LocalDate date,int target){if(date==null)throw new IllegalArgumentException("Study goal date cannot be null.");if(target<=0)throw new IllegalArgumentException("Study goal target must be greater than zero.");int studied=databaseManager.getAllStudySessions().stream().filter(s->s.getStartTime().toLocalDate().equals(date)).mapToInt(StudySession::getDurationMinutes).sum();return new DailyStudyGoal(date,target,studied);}
    public int getCourseStudyTargetMinutes(int courseId){requireCourse(courseId);String saved=databaseManager.getSetting(COURSE_STUDY_TARGET_PREFIX+courseId);if(saved==null)return DEFAULT_COURSE_STUDY_TARGET;try{int v=Integer.parseInt(saved);return v>0?v:DEFAULT_COURSE_STUDY_TARGET;}catch(NumberFormatException e){return DEFAULT_COURSE_STUDY_TARGET;}} public void setCourseStudyTargetMinutes(int courseId,int target){requireCourse(courseId);if(target<=0)throw new IllegalArgumentException("Course study target must be greater than zero.");databaseManager.setSetting(COURSE_STUDY_TARGET_PREFIX+courseId,Integer.toString(target));} public CourseStudyGoal getCourseStudyGoal(int courseId){return getCourseStudyGoal(courseId,LocalDate.now());} public CourseStudyGoal getCourseStudyGoal(int courseId,LocalDate referenceDate){Course course=requireCourse(courseId);if(referenceDate==null)throw new IllegalArgumentException("Course study goal reference date cannot be null.");LocalDate weekStart=referenceDate.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY));LocalDateTime start=weekStart.atStartOfDay(),end=weekStart.plusDays(7).atStartOfDay();int studied=databaseManager.getStudySessionsByCourse(courseId).stream().filter(s->!s.getStartTime().isBefore(start)&&s.getStartTime().isBefore(end)).mapToInt(StudySession::getDurationMinutes).sum();return new CourseStudyGoal(course,getCourseStudyTargetMinutes(courseId),studied);}

    public List<StudyRecommendation> getStudyRecommendations(){return getStudyRecommendations(LocalDateTime.now());}
    public List<StudyRecommendation> getStudyRecommendations(LocalDateTime now){if(now==null)throw new IllegalArgumentException("Recommendation reference time cannot be null.");return databaseManager.getAllCourses().stream().map(course->buildRecommendation(course,now)).sorted(Comparator.comparingInt(StudyRecommendation::score).reversed().thenComparing(r->r.course().getCode())).toList();}
    private StudyRecommendation buildRecommendation(Course course,LocalDateTime now){List<Assignment> pending=databaseManager.getAssignmentsByCourse(course.getId()).stream().filter(a->!a.isCompleted()).toList();int high=(int)pending.stream().filter(a->a.getPriority()==Assignment.Priority.HIGH).count();boolean dueSoon=pending.stream().anyMatch(a->!a.getDueDate().isBefore(now)&&!a.getDueDate().isAfter(now.plusHours(48)));boolean overdue=pending.stream().anyMatch(a->a.getDueDate().isBefore(now));CourseStudyGoal goal=getCourseStudyGoal(course.getId(),now.toLocalDate());int score=Math.min(40,goal.remainingMinutes()/15)+pending.size()*8+high*12+(dueSoon?25:0)+(overdue?30:0);String reason;if(overdue)reason="Overdue work needs attention";else if(dueSoon)reason="Assignment due within 48 hours";else if(high>0)reason="High-priority assignment pending";else if(goal.remainingMinutes()>0)reason="Weekly study goal needs progress";else if(!pending.isEmpty())reason="Pending coursework remains";else reason="Weekly goal is on track";return new StudyRecommendation(course,score,goal.remainingMinutes(),pending.size(),high,dueSoon,reason);}

    public StudyProgressAnalytics getStudyProgressAnalytics(){return getStudyProgressAnalytics(LocalDate.now());} public StudyProgressAnalytics getStudyProgressAnalytics(LocalDate date){if(date==null)throw new IllegalArgumentException("Study progress reference date cannot be null.");LocalDate start=date.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)),end=start.plusDays(6);LocalDateTime a=start.atStartOfDay(),b=start.plusDays(7).atStartOfDay();List<StudySession> sessions=databaseManager.getAllStudySessions().stream().filter(s->!s.getStartTime().isBefore(a)).filter(s->s.getStartTime().isBefore(b)).toList();int total=sessions.stream().mapToInt(StudySession::getDurationMinutes).sum(),longest=sessions.stream().mapToInt(StudySession::getDurationMinutes).max().orElse(0);Set<LocalDate> days=sessions.stream().map(s->s.getStartTime().toLocalDate()).collect(Collectors.toSet());return new StudyProgressAnalytics(start,end,total,sessions.size(),days.size(),longest,days.isEmpty()?0.0:total/(double)days.size());}
    public StudyTrend getStudyTrend(){return getStudyTrend(LocalDate.now());} public StudyTrend getStudyTrend(LocalDate date){if(date==null)throw new IllegalArgumentException("Study trend reference date cannot be null.");LocalDate current=date.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)),previous=current.minusWeeks(1);LocalDateTime a=previous.atStartOfDay(),b=current.atStartOfDay(),c=current.plusWeeks(1).atStartOfDay();int pm=databaseManager.getAllStudySessions().stream().filter(s->!s.getStartTime().isBefore(a)&&s.getStartTime().isBefore(b)).mapToInt(StudySession::getDurationMinutes).sum();int cm=databaseManager.getAllStudySessions().stream().filter(s->!s.getStartTime().isBefore(b)&&s.getStartTime().isBefore(c)).mapToInt(StudySession::getDurationMinutes).sum();int change=cm-pm;return new StudyTrend(current,cm,pm,change,pm==0?0.0:change*100.0/pm);} public StudyStreak getStudyStreak(){return getStudyStreak(LocalDate.now());} public StudyStreak getStudyStreak(LocalDate date){if(date==null)throw new IllegalArgumentException("Study streak reference date cannot be null.");List<LocalDate> days=databaseManager.getAllStudySessions().stream().map(s->s.getStartTime().toLocalDate()).filter(d->!d.isAfter(date)).distinct().sorted().toList();if(days.isEmpty())return new StudyStreak(date,0,0,false,null);int longest=1,running=1;for(int i=1;i<days.size();i++){if(days.get(i).equals(days.get(i-1).plusDays(1)))running++;else running=1;longest=Math.max(longest,running);}LocalDate last=days.get(days.size()-1);int current=1;for(int i=days.size()-1;i>0;i--){if(days.get(i-1).equals(days.get(i).minusDays(1)))current++;else break;}return new StudyStreak(date,current,longest,last.equals(date),last);}
    public double getAssignmentCompletionPercentage(){List<Assignment>a=databaseManager.getAllAssignments();if(a.isEmpty())return 0.0;return a.stream().filter(Assignment::isCompleted).count()*100.0/a.size();} public DashboardSummary getDashboardSummary(){List<Course>c=databaseManager.getAllCourses();List<Assignment>a=databaseManager.getAllAssignments();int completed=(int)a.stream().filter(Assignment::isCompleted).count(),pending=a.size()-completed,overdue=(int)a.stream().filter(Assignment::isOverdue).count();return new DashboardSummary(c.size(),a.size(),pending,completed,overdue,getTotalStudyMinutes(),getAssignmentCompletionPercentage());} public DashboardAnalytics getDashboardAnalytics(){LocalDateTime now=LocalDateTime.now();List<Assignment>p=databaseManager.getAllAssignments().stream().filter(a->!a.isCompleted()).toList();int upcoming=(int)p.stream().filter(a->!a.getDueDate().isBefore(now)&&!a.getDueDate().isAfter(now.plusDays(7))).count(),high=(int)p.stream().filter(a->a.getPriority()==Assignment.Priority.HIGH).count();Assignment nearest=p.stream().filter(a->!a.getDueDate().isBefore(now)).min(Comparator.comparing(Assignment::getDueDate)).orElse(null);Course most=null;int max=0;for(Course c:databaseManager.getAllCourses()){int m=databaseManager.getStudySessionsByCourse(c.getId()).stream().mapToInt(StudySession::getDurationMinutes).sum();if(m>max){max=m;most=c;}}return new DashboardAnalytics(upcoming,high,nearest,most,max);}
    private Course requireCourse(int id){Course x=databaseManager.findCourseById(id);if(x==null)throw new IllegalArgumentException("Course does not exist: "+id);return x;} private Assignment requireAssignment(int id){Assignment x=databaseManager.findAssignmentById(id);if(x==null)throw new IllegalArgumentException("Assignment does not exist: "+id);return x;} private StudySession requireStudySession(int id){StudySession x=databaseManager.findStudySessionById(id);if(x==null)throw new IllegalArgumentException("Study session does not exist: "+id);return x;}
}
