package com.studysync;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

/** JavaFX desktop entry point for StudySync 2.0. */
public class StudySyncApplication extends Application {
    private StudySyncService service;
    private BorderPane root;
    private final VBox navigation = new VBox(8);
    private static final DateTimeFormatter DATE_TIME_FORMAT = DateTimeFormatter.ofPattern("MMM d, yyyy h:mm a");

    @Override public void start(Stage stage) {
        service = new StudySyncService(new DatabaseManager()); root = new BorderPane(); root.getStyleClass().add("app-root");
        root.setTop(createHeader()); root.setLeft(createNavigation()); showDashboard();
        Scene scene = new Scene(root, 1100, 700); scene.getStylesheets().add(getClass().getResource("/com/studysync/studysync.css").toExternalForm());
        stage.setTitle("StudySync"); stage.setMinWidth(900); stage.setMinHeight(600); stage.setScene(scene); stage.show();
    }

    private HBox createHeader() { Label title = new Label("StudySync"); title.getStyleClass().add("app-title"); Label subtitle = new Label("Plan. Study. Progress."); subtitle.getStyleClass().add("app-subtitle"); VBox branding = new VBox(3,title,subtitle); HBox header = new HBox(branding); header.setAlignment(Pos.CENTER_LEFT); header.setPadding(new Insets(18,28,18,28)); header.getStyleClass().add("app-header"); HBox.setHgrow(branding,Priority.ALWAYS); return header; }
    private VBox createNavigation() { navigation.getChildren().setAll(navigationButton("Dashboard",this::showDashboard),navigationButton("Courses",this::showCourses),navigationButton("Assignments",this::showAssignments),navigationButton("Study Sessions",this::showStudySessions),navigationButton("Workload",()->showPlaceholder("Workload","Plan upcoming assignments and academic workload."))); navigation.setPadding(new Insets(24,14,24,14)); navigation.setPrefWidth(205); navigation.getStyleClass().add("navigation"); return navigation; }
    private Button navigationButton(String text,Runnable action) { Button button=new Button(text); button.setMaxWidth(Double.MAX_VALUE); button.getStyleClass().add("navigation-button"); button.setOnAction(e->{setActiveNavigation(button);action.run();}); if(navigation.getChildren().isEmpty())button.getStyleClass().add("navigation-button-active"); return button; }
    private void setActiveNavigation(Button active) { navigation.getChildren().stream().filter(Button.class::isInstance).map(Button.class::cast).forEach(b->b.getStyleClass().remove("navigation-button-active")); active.getStyleClass().add("navigation-button-active"); }

    private void showDashboard() { DashboardSummary s=service.getDashboardSummary(); GridPane g=new GridPane(); g.setHgap(16);g.setVgap(16); g.add(createMetricCard("Courses",s.totalCourses()),0,0);g.add(createMetricCard("Pending",s.pendingAssignments()),1,0);g.add(createMetricCard("Completed",s.completedAssignments()),2,0);g.add(createMetricCard("Overdue",s.overdueAssignments()),0,1);g.add(createMetricCard("Study Minutes",s.totalStudyMinutes()),1,1);g.add(createMetricCard("Completion",String.format("%.1f%%",s.completionPercentage())),2,1); for(int i=0;i<3;i++){ColumnConstraints c=new ColumnConstraints();c.setPercentWidth(33.333);c.setHgrow(Priority.ALWAYS);g.getColumnConstraints().add(c);} setPage(pageContainer("Dashboard","A quick view of your courses, assignments, and study progress.",g)); }

    private void showCourses() { TextField code=new TextField();code.setPromptText("e.g. CSCI 2302"); TextField name=new TextField();name.setPromptText("e.g. Data Structures & Algorithms"); Button add=new Button("Add Course");add.getStyleClass().add("primary-button"); GridPane form=formGrid(); form.add(new Label("Course Code"),0,0);form.add(code,1,0);form.add(new Label("Course Name"),0,1);form.add(name,1,1);form.add(add,1,2); VBox list=new VBox(10);refreshCourseList(list); add.setOnAction(e->{try{service.createCourse(name.getText(),code.getText());name.clear();code.clear();refreshCourseList(list);}catch(RuntimeException ex){showError("Could not add course",ex.getMessage());}}); setPage(pageContainer("Courses","Add courses and keep your academic schedule organized.",new VBox(18,card("Add a Course",form),card("Your Courses",list)))); }
    private void refreshCourseList(VBox list) { List<Course> courses=service.getCourses();list.getChildren().clear(); if(courses.isEmpty()){addEmpty(list,"No courses yet. Add your first course above.");return;} for(Course c:courses){Label code=new Label(c.getCode());code.getStyleClass().add("course-code");Label name=new Label(c.getName());name.getStyleClass().add("course-name");HBox row=new HBox(new VBox(3,code,name));row.setPadding(new Insets(14));row.getStyleClass().add("course-row");list.getChildren().add(row);} }

    private void showAssignments() { List<Course> courses=service.getCourses(); if(courses.isEmpty()){setPage(pageContainer("Assignments","Manage deadlines, priorities, and completion status.",card("Assignments",styledLabel("Add a course before creating assignments.","placeholder-message"))));return;} ComboBox<Course> course=new ComboBox<>();course.getItems().addAll(courses);course.getSelectionModel().selectFirst();course.setMaxWidth(Double.MAX_VALUE); TextField title=new TextField();title.setPromptText("Assignment title");TextField desc=new TextField();desc.setPromptText("Description (optional)");DatePicker date=new DatePicker(LocalDate.now().plusDays(1));TextField time=new TextField("23:59");ComboBox<Assignment.Priority> priority=new ComboBox<>();priority.getItems().addAll(Assignment.Priority.values());priority.setValue(Assignment.Priority.MEDIUM);Button add=new Button("Add Assignment");add.getStyleClass().add("primary-button");GridPane form=formGrid();form.add(new Label("Course"),0,0);form.add(course,1,0);form.add(new Label("Title"),0,1);form.add(title,1,1);form.add(new Label("Description"),0,2);form.add(desc,1,2);form.add(new Label("Due Date"),0,3);form.add(date,1,3);form.add(new Label("Due Time"),0,4);form.add(time,1,4);form.add(new Label("Priority"),0,5);form.add(priority,1,5);form.add(add,1,6);VBox list=new VBox(10);refreshAssignmentList(list);add.setOnAction(e->{try{service.createAssignment(course.getValue().getId(),title.getText(),desc.getText(),LocalDateTime.of(date.getValue(),LocalTime.parse(time.getText().trim())),priority.getValue());title.clear();desc.clear();refreshAssignmentList(list);}catch(RuntimeException ex){showError("Could not add assignment",ex.getMessage());}});setPage(pageContainer("Assignments","Manage deadlines, priorities, and completion status.",new VBox(18,card("Add an Assignment",form),card("Your Assignments",list)))); }
    private void refreshAssignmentList(VBox list) { List<Assignment> assignments=service.getAssignments();list.getChildren().clear();if(assignments.isEmpty()){addEmpty(list,"No assignments yet.");return;}for(Assignment a:assignments){Label title=styledLabel(a.getTitle(),"assignment-title");Label meta=styledLabel("Due "+a.getDueDate().format(DATE_TIME_FORMAT)+"  •  "+a.getPriority()+"  •  "+(a.isCompleted()?"Completed":a.isOverdue()?"Overdue":"Pending"),"assignment-meta");Label desc=styledLabel(a.getDescription(),"course-name");desc.setWrapText(true);VBox details=new VBox(4,title,meta,desc);HBox.setHgrow(details,Priority.ALWAYS);Button status=new Button(a.isCompleted()?"Reopen":"Complete");status.getStyleClass().add("secondary-button");status.setOnAction(e->{try{if(a.isCompleted())service.reopenAssignment(a.getId());else service.completeAssignment(a.getId());refreshAssignmentList(list);}catch(RuntimeException ex){showError("Could not update assignment",ex.getMessage());}});HBox row=new HBox(14,details,status);row.setAlignment(Pos.CENTER_LEFT);row.setPadding(new Insets(14));row.getStyleClass().add("course-row");list.getChildren().add(row);} }

    private void showStudySessions() { List<Course> courses=service.getCourses(); if(courses.isEmpty()){setPage(pageContainer("Study Sessions","Record and review focused study time.",card("Study Sessions",styledLabel("Add a course before recording study sessions.","placeholder-message"))));return;} ComboBox<Course> course=new ComboBox<>();course.getItems().addAll(courses);course.getSelectionModel().selectFirst();course.setMaxWidth(Double.MAX_VALUE);DatePicker date=new DatePicker(LocalDate.now());TextField time=new TextField(LocalTime.now().withSecond(0).withNano(0).toString());time.setPromptText("HH:mm");TextField duration=new TextField();duration.setPromptText("Minutes");TextField notes=new TextField();notes.setPromptText("What did you study? (optional)");Button record=new Button("Record Session");record.getStyleClass().add("primary-button");GridPane form=formGrid();form.add(new Label("Course"),0,0);form.add(course,1,0);form.add(new Label("Date"),0,1);form.add(date,1,1);form.add(new Label("Start Time"),0,2);form.add(time,1,2);form.add(new Label("Duration"),0,3);form.add(duration,1,3);form.add(new Label("Notes"),0,4);form.add(notes,1,4);form.add(record,1,5);VBox list=new VBox(10);refreshStudySessionList(list);record.setOnAction(e->{try{int minutes=Integer.parseInt(duration.getText().trim());LocalDateTime start=LocalDateTime.of(date.getValue(),LocalTime.parse(time.getText().trim()));service.recordStudySession(course.getValue().getId(),start,minutes,notes.getText());duration.clear();notes.clear();refreshStudySessionList(list);}catch(NumberFormatException ex){showError("Could not record session","Duration must be a whole number of minutes.");}catch(RuntimeException ex){showError("Could not record session",ex.getMessage());}});Label total=styledLabel("Total study time: "+service.getTotalStudyMinutes()+" minutes","study-total");VBox history=new VBox(10,total,list);setPage(pageContainer("Study Sessions","Record and review focused study time.",new VBox(18,card("Record a Study Session",form),card("Study History",history)))); }
    private void refreshStudySessionList(VBox list) { List<StudySession> sessions=service.getStudySessions();list.getChildren().clear();if(sessions.isEmpty()){addEmpty(list,"No study sessions recorded yet.");return;}for(StudySession s:sessions){Course course=service.getCourses().stream().filter(c->c.getId()==s.getCourseId()).findFirst().orElse(null);String courseText=course==null?"Course #"+s.getCourseId():course.getCode();Label title=styledLabel(courseText+" • "+s.getDurationMinutes()+" minutes","assignment-title");Label meta=styledLabel(s.getStartTime().format(DATE_TIME_FORMAT),"assignment-meta");Label notes=styledLabel(s.getNotes().isBlank()?"No notes":s.getNotes(),"course-name");notes.setWrapText(true);VBox details=new VBox(4,title,meta,notes);HBox row=new HBox(details);row.setPadding(new Insets(14));row.getStyleClass().add("course-row");list.getChildren().add(row);} }

    private GridPane formGrid(){GridPane form=new GridPane();form.setHgap(12);form.setVgap(10);ColumnConstraints input=new ColumnConstraints();input.setHgrow(Priority.ALWAYS);form.getColumnConstraints().addAll(new ColumnConstraints(),input);return form;}
    private Label styledLabel(String text,String style){Label l=new Label(text);l.getStyleClass().add(style);return l;}
    private void addEmpty(VBox list,String text){list.getChildren().add(styledLabel(text,"placeholder-message"));}
    private VBox card(String title,Node content){Label heading=styledLabel(title,"card-title");VBox card=new VBox(12,heading,content);card.setPadding(new Insets(20));card.getStyleClass().add("content-card");return card;}
    private void showError(String title,String message){Alert alert=new Alert(Alert.AlertType.ERROR);alert.setTitle("StudySync");alert.setHeaderText(title);alert.setContentText(message);alert.showAndWait();}
    private void showPlaceholder(String title,String description){setPage(pageContainer(title,description,card(title,styledLabel(title+" workspace is ready for its v2.0 feature screen.","placeholder-message"))));}
    private VBox pageContainer(String titleText,String descriptionText,Node content){Label title=styledLabel(titleText,"section-title");Label description=styledLabel(descriptionText,"section-description");VBox page=new VBox(12,title,description,content);page.setPadding(new Insets(30));VBox.setMargin(content,new Insets(14,0,0,0));return page;}
    private void setPage(Node page){ScrollPane scroll=new ScrollPane(page);scroll.setFitToWidth(true);scroll.setFitToHeight(true);scroll.getStyleClass().add("content-scroll");root.setCenter(scroll);}
    private VBox createMetricCard(String labelText,Object valueText){Label value=styledLabel(String.valueOf(valueText),"metric-value");Label label=styledLabel(labelText,"metric-label");VBox card=new VBox(6,value,label);card.setPadding(new Insets(20));card.setMinHeight(120);card.setMaxWidth(Double.MAX_VALUE);card.getStyleClass().add("metric-card");return card;}
    public static void main(String[] args){launch(args);}
}
